[package]
name = "hello"
version = "0.1.0"
authors = ["Anatol Ulrich <anatol.ulrich@ferrous-systems.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]


[dependencies]
cty = "*"

[build-dependencies]
bindgen = "*"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
